package com.cbrothercoder.demo.common.dao.po.autogen;

import java.io.Serializable;

public class TxSequence implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tx_sequence
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1009L;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tx_sequence.table_name
     *
     * @mbg.generated
     */
    private String tableName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tx_sequence.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tx_sequence.table_name
     *
     * @return the value of tx_sequence.table_name
     *
     * @mbg.generated
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tx_sequence.table_name
     *
     * @param tableName the value for tx_sequence.table_name
     *
     * @mbg.generated
     */
    public void setTableName(String tableName) {
        this.tableName = tableName == null ? null : tableName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tx_sequence.id
     *
     * @return the value of tx_sequence.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tx_sequence.id
     *
     * @param id the value for tx_sequence.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }
}
